name: Events Demo 1
on:
  pull_request:
    types: -opened
    branches: -main
      -dev
  workflow_dispatch:
  push:
    branches: -main
      -dev
    paths: -'.github/workflows/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Deploy project
        run: echo "Deploying..."
